---

- name: reload systemctl
  command: systemctl daemon-reload

- name: restart grafana
  systemd:
    name: grafana-server
    state: restarted

- name: restart prometheus
  systemd:
    name: prometheus
    state: restarted

- name: restart blackbox_exporter
  systemd:
    name: blackbox_exporter
    state: restarted
