---

- name: restart grafana
  systemd:
    name: grafana-server
    daemon_reload: yes
    state: restarted

- name: restart prometheus
  systemd:
    name: prometheus
    daemon_reload: yes
    state: restarted

- name: restart blackbox_exporter
  systemd:
    name: blackbox_exporter
    daemon_reload: yes
    state: restarted
