---

- name: Creating caddy user group
  group:
    name: "{{ caddy_group_name }}"
    system: yes
  become: true

- name: Creating caddy user
  user:
    name: "{{ caddy_user_name }}"
    group: "{{ caddy_group_name }}"
    system: yes
    shell: "/sbin/nologin"
    comment: "{{ caddy_user_name }} nologin User"
    create_home : yes
    home: /var/lib/caddy
    state: present

- name: Download caddy
  unarchive:
    src: "https://github.com/caddyserver/caddy/releases/download/v{{ caddy_version }}/caddy_{{ caddy_version }}_linux_amd64.tar.gz"
    dest: /tmp/
    remote_src: yes


- name: Copy caddy file to bin
  copy:
    src: "/tmp/caddy"
    dest: "/usr/local/bin/caddy"
    owner: "{{ caddy_user_name }}"
    group: "{{ caddy_group_name }}"
    remote_src: yes
    mode: 0755

- name: Delete caddy tmp file
  file:
    path: "/tmp/caddy"
    state: absent

- name: Creates directory
  file:
    path: "/etc/caddy/"
    state: directory
    owner: "{{ caddy_user_name }}"
    group: "{{ caddy_group_name }}"
    mode: 0755

- name: config file
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile

- name: Create Unit file for caddy
  template: src=caddy.service.j2 dest=/etc/systemd/system/caddy.service mode=644
  notify:
    - reload systemctl

- name: start caddy service
  service: name=caddy.service state=restarted enabled=yes

- name: Check if caddy is accessible
  uri:
    url: https://{{ inventory_hostname }}/
    method: GET
    status_code: 200
