---

- name: install required grafana packages
  apt:
    pkg:
      - adduser
      - libfontconfig1
    state: present
    update_cache: yes

- name: install grafana
  apt:
    deb: https://dl.grafana.com/oss/release/grafana_{{ grafana_version }}_amd64.deb
  notify:
    # The deb technically already restarts grafana and triggers the systemd reload
    - restart grafana

- name: start/enable grafana service
  service: name=grafana-server.service state=started enabled=yes

- name: check if grafana is accessible.
  uri:
    url: http://{{ inventory_hostname }}:3000
    method: GET
    status_code: 200
