---

- name: set a hostname
  hostname:
    name: "{{ inventory_hostname }}"

- include: grafana.yml
  become: yes
  tags:
    - grafana

- include: prometheus.yml
  become: yes
  tags:
    - prometheus

- include: blackbox_exporter.yml
