---

libnice_version: "0.1.18"
libsrtp_version: "v2.3.0"
janusgateway_version: "v0.10.9"
janus_ftl_plugin_version: "master"

glimesh_client_id: some_key
glimesh_client_secret: some_key
ftl_orchestrator_psk: some_key